name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pre-setup
      run: sudo apt-get install libzip-dev
    - name: setup
      run: bin/setup.sh
    - name: test
      run: bin/test.sh
